"""Ironflow Python SDK - generated client surface.

GENERATED by cmd/sdk-gen from sdk-manifest.json. Do not edit.

Source route set: 550a32a27aa48bc2

Only the thin per-endpoint methods live here. The transport, error model, and
retry policy are hand-written in _http.py so that ruff, mypy, and pytest can
see them as ordinary Python.

A query parameter whose name is a Python keyword, or which collides with a
path parameter, gets trailing underscores until it is free ("from" becomes
"from_"). Only the keyword argument is renamed; the wire name is unchanged.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, BinaryIO, cast
from urllib.parse import quote

from . import models
from ._http import BaseClient, BinaryResponse, IronflowError

# Re-exported for backwards compatibility: 'from ironflow.client import
# IronflowError' predates the _http.py split and is used in the wild.
__all__ = ["IronflowClient", "IronflowError"]


class IronflowClient(BaseClient):
    """Ironflow REST API client.

    Usage::

        client = IronflowClient(server_url="http://localhost:9123")
        events = client.events_list()
        event = client.events_get("evt_abc123")

    Methods on routes the manifest annotates with schemas are typed: they
    return models.* TypedDicts and take their query parameters as keyword
    arguments. Every other method still returns Any and takes no query
    parameters, because the manifest carries nothing to type them with.

    Headers declared by the route manifest are typed keyword arguments on the
    corresponding method. Use BaseClient.request() for undeclared headers and
    for query parameters on a route that is not yet annotated.
    """

    # No __init__ here on purpose: inheriting BaseClient.__init__ keeps every
    # knob reachable (max_attempts, retry_methods, backoff, total_timeout).
    # A narrowed generated signature would silently hide them.

    # ── APIKeys ─────────────────────────────────────

    def api_keys_create(self, body: models.CreateAPIKeyRequest | None = None) -> models.CreateAPIKeyResponse:
        """POST /api/v1/apikeys"""
        path = "/api/v1/apikeys"
        return cast("models.CreateAPIKeyResponse", self._request("POST", path, body))

    def api_keys_delete(self, id: str) -> Any:
        """DELETE /api/v1/apikeys/{id}"""
        path = f"/api/v1/apikeys/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def api_keys_get(self, id: str) -> models.ApiKeyResponse:
        """GET /api/v1/apikeys/{id}"""
        path = f"/api/v1/apikeys/{quote(id, safe='')}"
        return cast("models.ApiKeyResponse", self._request("GET", path))

    def api_keys_list(self, *, platform: bool | None = None) -> list[models.ApiKeyResponse]:
        """GET /api/v1/apikeys"""
        path = "/api/v1/apikeys"
        return cast("list[models.ApiKeyResponse]", self._request("GET", path, None, params={"platform": platform}))

    def api_keys_rotate(self, id: str, body: Any = None) -> models.CreateAPIKeyResponse:
        """POST /api/v1/apikeys/{id}/rotate"""
        path = f"/api/v1/apikeys/{quote(id, safe='')}/rotate"
        return cast("models.CreateAPIKeyResponse", self._request("POST", path, body))

    def api_keys_update_roles(self, id: str, body: models.ReplaceRolesRequest | None = None) -> models.ApiKeyResponse:
        """PUT /api/v1/apikeys/{id}/roles"""
        path = f"/api/v1/apikeys/{quote(id, safe='')}/roles"
        return cast("models.ApiKeyResponse", self._request("PUT", path, body))

    # ── Audit ─────────────────────────────────────

    def audit_list(self, *, action: str | None = None, api_key_id: str | None = None, cursor: str | None = None, event_type: str | None = None, from_: str | None = None, function_id: str | None = None, limit: int | None = None, run_id: str | None = None, to: str | None = None) -> models.RunAuditResponse:
        """GET /api/v1/audit"""
        path = "/api/v1/audit"
        return cast("models.RunAuditResponse", self._request("GET", path, None, params={"action": action, "api_key_id": api_key_id, "cursor": cursor, "event_type": event_type, "from": from_, "function_id": function_id, "limit": limit, "run_id": run_id, "to": to}))

    def audit_list_settings(self) -> models.AuditSettingsResponse:
        """GET /api/v1/audit/settings"""
        path = "/api/v1/audit/settings"
        return cast("models.AuditSettingsResponse", self._request("GET", path))

    # ── Capacity ─────────────────────────────────────

    def capacity_list_buckets(self, *, env: str | None = None, function: str | None = None, limit: int | None = None) -> list[models.DispatchBucketRow]:
        """GET /api/v1/capacity/buckets"""
        path = "/api/v1/capacity/buckets"
        return cast("list[models.DispatchBucketRow]", self._request("GET", path, None, params={"env": env, "function": function, "limit": limit}))

    def capacity_list_credits(self, *, env: str | None = None, function: str | None = None, limit: int | None = None) -> list[models.WorkerCredit]:
        """GET /api/v1/capacity/credits"""
        path = "/api/v1/capacity/credits"
        return cast("list[models.WorkerCredit]", self._request("GET", path, None, params={"env": env, "function": function, "limit": limit}))

    def capacity_list_lanes(self, *, env: str | None = None, function: str | None = None, limit: int | None = None) -> list[models.ConcurrencyLane]:
        """GET /api/v1/capacity/lanes"""
        path = "/api/v1/capacity/lanes"
        return cast("list[models.ConcurrencyLane]", self._request("GET", path, None, params={"env": env, "function": function, "limit": limit}))

    def capacity_list_leases(self, *, env: str | None = None, function: str | None = None, limit: int | None = None) -> list[models.ConcurrencyLease]:
        """GET /api/v1/capacity/leases"""
        path = "/api/v1/capacity/leases"
        return cast("list[models.ConcurrencyLease]", self._request("GET", path, None, params={"env": env, "function": function, "limit": limit}))

    def capacity_list_queue(self, *, env: str | None = None, function: str | None = None, limit: int | None = None) -> list[models.DispatchSegment]:
        """GET /api/v1/capacity/queue"""
        path = "/api/v1/capacity/queue"
        return cast("list[models.DispatchSegment]", self._request("GET", path, None, params={"env": env, "function": function, "limit": limit}))

    def capacity_list_sessions(self, *, env: str | None = None, function: str | None = None, limit: int | None = None) -> list[models.WorkerSession]:
        """GET /api/v1/capacity/sessions"""
        path = "/api/v1/capacity/sessions"
        return cast("list[models.WorkerSession]", self._request("GET", path, None, params={"env": env, "function": function, "limit": limit}))

    def capacity_list_stats(self) -> list[models.CapacityStat]:
        """GET /api/v1/capacity/stats"""
        path = "/api/v1/capacity/stats"
        return cast("list[models.CapacityStat]", self._request("GET", path))

    # ── CircuitBreakers ─────────────────────────────────────

    def circuit_breakers_list(self) -> list[models.BreakerState]:
        """GET /api/v1/circuit-breakers"""
        path = "/api/v1/circuit-breakers"
        return cast("list[models.BreakerState]", self._request("GET", path))

    def circuit_breakers_reset(self, key: str, body: Any = None) -> models.BreakerState:
        """POST /api/v1/circuit-breakers/{key}/reset"""
        path = f"/api/v1/circuit-breakers/{quote(key, safe='')}/reset"
        return cast("models.BreakerState", self._request("POST", path, body))

    # ── Cluster ─────────────────────────────────────

    def cluster_rotate_token(self, body: models.RotateTokenRequest | None = None, *, idempotency_key: str | None = None) -> models.RotateTokenResponse:
        """POST /api/v1/cluster/rotate-token"""
        path = "/api/v1/cluster/rotate-token"
        return cast("models.RotateTokenResponse", self._request("POST", path, body, headers={"Idempotency-Key": idempotency_key}))

    # ── Config ─────────────────────────────────────

    def config_create(self, name: str, body: dict[str, Any] | None = None) -> models.ConfigSetResult:
        """POST /api/v1/config/{name}"""
        path = f"/api/v1/config/{quote(name, safe='')}"
        return cast("models.ConfigSetResult", self._request("POST", path, body))

    def config_delete(self, name: str) -> Any:
        """DELETE /api/v1/config/{name}"""
        path = f"/api/v1/config/{quote(name, safe='')}"
        return self._request("DELETE", path)

    def config_get(self, name: str) -> models.ConfigResponse:
        """GET /api/v1/config/{name}"""
        path = f"/api/v1/config/{quote(name, safe='')}"
        return cast("models.ConfigResponse", self._request("GET", path))

    def config_list(self) -> models.ListConfigsResponse:
        """GET /api/v1/config"""
        path = "/api/v1/config"
        return cast("models.ListConfigsResponse", self._request("GET", path))

    def config_patch(self, name: str, body: dict[str, Any] | None = None) -> models.ConfigSetResult:
        """PATCH /api/v1/config/{name}"""
        path = f"/api/v1/config/{quote(name, safe='')}"
        return cast("models.ConfigSetResult", self._request("PATCH", path, body))

    # ── Debounce ─────────────────────────────────────

    def debounce_delete_entries(self, env_id: str, fn_id: str, key: str) -> Any:
        """DELETE /api/v1/debounce/entries/{envID}/{fnID}/{key}"""
        path = f"/api/v1/debounce/entries/{quote(env_id, safe='')}/{quote(fn_id, safe='')}/{quote(key, safe='')}"
        return self._request("DELETE", path)

    def debounce_list_entries(self) -> list[models.DebounceEntryView]:
        """GET /api/v1/debounce/entries"""
        path = "/api/v1/debounce/entries"
        return cast("list[models.DebounceEntryView]", self._request("GET", path))

    # ── Environments ─────────────────────────────────────

    def environments_create(self, body: models.CreateEnvironmentRequest | None = None) -> models.Environment:
        """POST /api/v1/environments"""
        path = "/api/v1/environments"
        return cast("models.Environment", self._request("POST", path, body))

    def environments_delete(self, id: str) -> models.DeleteEnvironmentResponse:
        """DELETE /api/v1/environments/{id}"""
        path = f"/api/v1/environments/{quote(id, safe='')}"
        return cast("models.DeleteEnvironmentResponse", self._request("DELETE", path))

    def environments_list(self, *, project_id: str | None = None) -> list[models.EnvResponse]:
        """GET /api/v1/environments"""
        path = "/api/v1/environments"
        return cast("list[models.EnvResponse]", self._request("GET", path, None, params={"project_id": project_id}))

    def environments_update(self, id: str, body: models.UpdateEnvironmentRequest | None = None) -> models.Environment:
        """PUT /api/v1/environments/{id}"""
        path = f"/api/v1/environments/{quote(id, safe='')}"
        return cast("models.Environment", self._request("PUT", path, body))

    # ── Events ─────────────────────────────────────

    def events_get(self, id: str) -> models.EventResponse:
        """GET /api/v1/events/{id}"""
        path = f"/api/v1/events/{quote(id, safe='')}"
        return cast("models.EventResponse", self._request("GET", path))

    def events_list(self, *, before: str | None = None, cursor: str | None = None, limit: int | None = None, name: str | None = None, names: str | None = None, search: str | None = None, since: str | None = None, source: str | None = None, until: str | None = None) -> models.ListEventsResponse:
        """GET /api/v1/events"""
        path = "/api/v1/events"
        return cast("models.ListEventsResponse", self._request("GET", path, None, params={"before": before, "cursor": cursor, "limit": limit, "name": name, "names": names, "search": search, "since": since, "source": source, "until": until}))

    def events_list_names(self, *, since: str | None = None, source: str | None = None, until: str | None = None) -> models.ListEventNamesResponse:
        """GET /api/v1/events/names"""
        path = "/api/v1/events/names"
        return cast("models.ListEventNamesResponse", self._request("GET", path, None, params={"since": since, "source": source, "until": until}))

    # ── Files ─────────────────────────────────────

    def files_buckets(self, body: models.FilesCreateBucketRequest | None = None) -> models.FilesBucketJSON:
        """POST /api/v1/files/buckets"""
        path = "/api/v1/files/buckets"
        return cast("models.FilesBucketJSON", self._request("POST", path, body))

    def files_buckets_copy(self, bucket: str, body: models.FilesCopyRequest | None = None) -> models.FileInfo:
        """POST /api/v1/files/buckets/{bucket}/copy"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/copy"
        return cast("models.FileInfo", self._request("POST", path, body))

    def files_buckets_move(self, bucket: str, body: models.FilesMoveRequest | None = None) -> models.FileInfo:
        """POST /api/v1/files/buckets/{bucket}/move"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/move"
        return cast("models.FileInfo", self._request("POST", path, body))

    def files_buckets_move_prefix(self, bucket: str, body: models.FilesMovePrefixRequest | None = None) -> models.FilesMovePrefixResponse:
        """POST /api/v1/files/buckets/{bucket}/move-prefix"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/move-prefix"
        return cast("models.FilesMovePrefixResponse", self._request("POST", path, body))

    def files_buckets_signed_urls_download(self, bucket: str, body: models.FilesSignDownloadRequest | None = None) -> models.FilesSignedURLResponse:
        """POST /api/v1/files/buckets/{bucket}/signed-urls/download"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/signed-urls/download"
        return cast("models.FilesSignedURLResponse", self._request("POST", path, body))

    def files_buckets_signed_urls_upload(self, bucket: str, body: models.FilesSignUploadRequest | None = None) -> models.FilesSignedURLResponse:
        """POST /api/v1/files/buckets/{bucket}/signed-urls/upload"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/signed-urls/upload"
        return cast("models.FilesSignedURLResponse", self._request("POST", path, body))

    def files_delete_buckets(self, bucket: str) -> Any:
        """DELETE /api/v1/files/buckets/{bucket}"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}"
        return self._request("DELETE", path)

    def files_delete_buckets_objects(self, bucket: str, path: str) -> Any:
        """DELETE /api/v1/files/buckets/{bucket}/objects/{path...}"""
        url_path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/objects/{quote(path, safe='/')}"
        return self._request("DELETE", url_path)

    def files_get_buckets(self, bucket: str) -> models.FilesBucketJSON:
        """GET /api/v1/files/buckets/{bucket}"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}"
        return cast("models.FilesBucketJSON", self._request("GET", path))

    def files_get_buckets_info(self, bucket: str, path: str) -> models.FileInfo:
        """GET /api/v1/files/buckets/{bucket}/info/{path...}"""
        url_path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/info/{quote(path, safe='/')}"
        return cast("models.FileInfo", self._request("GET", url_path))

    def files_get_buckets_objects(self, bucket: str, path: str, *, if_match: str | None = None, range: str | None = None) -> BinaryResponse:
        """GET /api/v1/files/buckets/{bucket}/objects/{path...}"""
        url_path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/objects/{quote(path, safe='/')}"
        return self._request_stream("GET", url_path, headers={"If-Match": if_match, "Range": range})

    def files_list_buckets(self) -> models.FilesListBucketsResponse:
        """GET /api/v1/files/buckets"""
        path = "/api/v1/files/buckets"
        return cast("models.FilesListBucketsResponse", self._request("GET", path))

    def files_list_buckets_objects(self, bucket: str, *, cursor: str | None = None, delimiter: str | None = None, limit: int | None = None, prefix: str | None = None) -> models.FilesListResponse:
        """GET /api/v1/files/buckets/{bucket}/objects"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/objects"
        return cast("models.FilesListResponse", self._request("GET", path, None, params={"cursor": cursor, "delimiter": delimiter, "limit": limit, "prefix": prefix}))

    def files_list_signed(self, *, if_match: str | None = None, range: str | None = None, token: str | None = None) -> BinaryResponse:
        """GET /api/v1/files/signed"""
        path = "/api/v1/files/signed"
        return self._request_stream("GET", path, headers={"If-Match": if_match, "Range": range}, params={"token": token})

    def files_patch_buckets(self, bucket: str, body: models.FilesUpdateBucketRequest | None = None) -> models.FilesBucketJSON:
        """PATCH /api/v1/files/buckets/{bucket}"""
        path = f"/api/v1/files/buckets/{quote(bucket, safe='')}"
        return cast("models.FilesBucketJSON", self._request("PATCH", path, body))

    def files_update_buckets_objects(self, bucket: str, path: str, body: bytes | BinaryIO, *, content_type: str, if_match: str | None = None, if_none_match: str | None = None, extra_headers: Mapping[str, str] | None = None) -> models.FileInfo:
        """PUT /api/v1/files/buckets/{bucket}/objects/{path...}"""
        url_path = f"/api/v1/files/buckets/{quote(bucket, safe='')}/objects/{quote(path, safe='/')}"
        return cast("models.FileInfo", self._request_binary("PUT", url_path, body, headers={**(extra_headers or {}), "Content-Type": content_type, "If-Match": if_match, "If-None-Match": if_none_match}))

    def files_update_signed(self, body: bytes | BinaryIO, *, content_type: str, token: str | None = None, extra_headers: Mapping[str, str] | None = None) -> models.FileInfo:
        """PUT /api/v1/files/signed"""
        path = "/api/v1/files/signed"
        return cast("models.FileInfo", self._request_binary("PUT", path, body, headers={**(extra_headers or {}), "Content-Type": content_type}, params={"token": token}))

    # ── Flow ─────────────────────────────────────

    def flow_list_emit_edges(self) -> models.FlowEmitEdgesResponse:
        """GET /api/v1/flow/emit-edges"""
        path = "/api/v1/flow/emit-edges"
        return cast("models.FlowEmitEdgesResponse", self._request("GET", path))

    def flow_list_invoke_edges(self) -> models.FlowInvokeEdgesResponse:
        """GET /api/v1/flow/invoke-edges"""
        path = "/api/v1/flow/invoke-edges"
        return cast("models.FlowInvokeEdgesResponse", self._request("GET", path))

    def flow_list_stream_edges(self) -> models.FlowStreamEdgesResponse:
        """GET /api/v1/flow/stream-edges"""
        path = "/api/v1/flow/stream-edges"
        return cast("models.FlowStreamEdgesResponse", self._request("GET", path))

    def flow_list_topic_edges(self) -> models.FlowTopicEdgesResponse:
        """GET /api/v1/flow/topic-edges"""
        path = "/api/v1/flow/topic-edges"
        return cast("models.FlowTopicEdgesResponse", self._request("GET", path))

    def flow_list_wait_edges(self) -> models.FlowWaitEdgesResponse:
        """GET /api/v1/flow/wait-edges"""
        path = "/api/v1/flow/wait-edges"
        return cast("models.FlowWaitEdgesResponse", self._request("GET", path))

    def flow_list_webhooks(self) -> models.WebhookFlowData:
        """GET /api/v1/flow/webhooks"""
        path = "/api/v1/flow/webhooks"
        return cast("models.WebhookFlowData", self._request("GET", path))

    # ── KV ─────────────────────────────────────

    def kv_buckets(self, body: models.CreateBucketRequest | None = None) -> models.BucketInfo:
        """POST /api/v1/kv/buckets"""
        path = "/api/v1/kv/buckets"
        return cast("models.BucketInfo", self._request("POST", path, body))

    def kv_delete_buckets(self, bucket: str) -> Any:
        """DELETE /api/v1/kv/buckets/{bucket}"""
        path = f"/api/v1/kv/buckets/{quote(bucket, safe='')}"
        return self._request("DELETE", path)

    def kv_delete_buckets_keys(self, bucket: str, key: str, *, purge: bool | None = None) -> Any:
        """DELETE /api/v1/kv/buckets/{bucket}/keys/{key...}"""
        path = f"/api/v1/kv/buckets/{quote(bucket, safe='')}/keys/{quote(key, safe='')}"
        return self._request("DELETE", path, None, params={"purge": purge})

    def kv_get_buckets(self, bucket: str) -> models.BucketInfo:
        """GET /api/v1/kv/buckets/{bucket}"""
        path = f"/api/v1/kv/buckets/{quote(bucket, safe='')}"
        return cast("models.BucketInfo", self._request("GET", path))

    def kv_get_buckets_keys(self, bucket: str, key: str) -> models.KVEntry:
        """GET /api/v1/kv/buckets/{bucket}/keys/{key...}"""
        path = f"/api/v1/kv/buckets/{quote(bucket, safe='')}/keys/{quote(key, safe='')}"
        return cast("models.KVEntry", self._request("GET", path))

    def kv_list_buckets(self) -> models.ListBucketsResponse:
        """GET /api/v1/kv/buckets"""
        path = "/api/v1/kv/buckets"
        return cast("models.ListBucketsResponse", self._request("GET", path))

    def kv_list_buckets_keys(self, bucket: str, *, filter: str | None = None) -> models.ListKeysResponse:
        """GET /api/v1/kv/buckets/{bucket}/keys"""
        path = f"/api/v1/kv/buckets/{quote(bucket, safe='')}/keys"
        return cast("models.ListKeysResponse", self._request("GET", path, None, params={"filter": filter}))

    def kv_update_buckets_keys(self, bucket: str, key: str, body: Any = None, *, if_match: str | None = None, if_none_match: str | None = None) -> models.PutKeyResponse:
        """PUT /api/v1/kv/buckets/{bucket}/keys/{key...}"""
        path = f"/api/v1/kv/buckets/{quote(bucket, safe='')}/keys/{quote(key, safe='')}"
        return cast("models.PutKeyResponse", self._request("PUT", path, body, headers={"If-Match": if_match, "If-None-Match": if_none_match}))

    # ── Orgs ─────────────────────────────────────

    def orgs_create(self, body: models.CreateOrgRequest | None = None) -> models.Organization:
        """POST /api/v1/orgs"""
        path = "/api/v1/orgs"
        return cast("models.Organization", self._request("POST", path, body))

    def orgs_create_orgs(self, body: models.CreateOrgRequest | None = None) -> models.Organization:
        """POST /api/v1/platform/orgs"""
        path = "/api/v1/platform/orgs"
        return cast("models.Organization", self._request("POST", path, body))

    def orgs_delete(self, id: str) -> Any:
        """DELETE /api/v1/orgs/{id}"""
        path = f"/api/v1/orgs/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def orgs_get(self, id: str) -> models.Organization:
        """GET /api/v1/orgs/{id}"""
        path = f"/api/v1/orgs/{quote(id, safe='')}"
        return cast("models.Organization", self._request("GET", path))

    def orgs_list(self) -> list[models.Organization]:
        """GET /api/v1/orgs"""
        path = "/api/v1/orgs"
        return cast("list[models.Organization]", self._request("GET", path))

    def orgs_patch(self, id: str, body: models.UpdateOrgRequest | None = None) -> models.Organization:
        """PATCH /api/v1/orgs/{id}"""
        path = f"/api/v1/orgs/{quote(id, safe='')}"
        return cast("models.Organization", self._request("PATCH", path, body))

    # ── Outbox ─────────────────────────────────────

    def outbox_dead_letter_requeue(self, event_id: str, body: Any = None, *, x_ironflow_environment: str | None = None, env: str | None = None) -> models.DlqActionResponse:
        """POST /api/v1/outbox/dead-letter/{eventID}/requeue"""
        path = f"/api/v1/outbox/dead-letter/{quote(event_id, safe='')}/requeue"
        return cast("models.DlqActionResponse", self._request("POST", path, body, params={"env": env}, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    def outbox_delete_dead_letter(self, event_id: str, *, x_ironflow_environment: str | None = None, env: str | None = None) -> models.DlqActionResponse:
        """DELETE /api/v1/outbox/dead-letter/{eventID}"""
        path = f"/api/v1/outbox/dead-letter/{quote(event_id, safe='')}"
        return cast("models.DlqActionResponse", self._request("DELETE", path, None, params={"env": env}, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    def outbox_list_dead_letter(self, *, x_ironflow_environment: str | None = None, env: str | None = None, limit: int | None = None, offset: int | None = None) -> models.DlqListResponse:
        """GET /api/v1/outbox/dead-letter"""
        path = "/api/v1/outbox/dead-letter"
        return cast("models.DlqListResponse", self._request("GET", path, None, params={"env": env, "limit": limit, "offset": offset}, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    # ── Platform ─────────────────────────────────────

    def platform_auth_login(self, body: models.PlatformLoginRequest | None = None) -> models.PlatformLoginResponse:
        """POST /api/v1/platform/auth/login"""
        path = "/api/v1/platform/auth/login"
        return cast("models.PlatformLoginResponse", self._request("POST", path, body))

    def platform_bootstrap(self, body: models.PlatformBootstrapRequest | None = None) -> models.PlatformBootstrapResponse:
        """POST /api/v1/platform/bootstrap"""
        path = "/api/v1/platform/bootstrap"
        return cast("models.PlatformBootstrapResponse", self._request("POST", path, body))

    # ── PlatformAudit ─────────────────────────────────────

    def platform_audit_list(self, *, cursor: str | None = None, event_type: str | None = None, from_: str | None = None, impersonated_org_id: str | None = None, limit: int | None = None, platform_key_id: str | None = None, to: str | None = None) -> models.PlatformAuditResponse:
        """GET /api/v1/platform/audit"""
        path = "/api/v1/platform/audit"
        return cast("models.PlatformAuditResponse", self._request("GET", path, None, params={"cursor": cursor, "event_type": event_type, "from": from_, "impersonated_org_id": impersonated_org_id, "limit": limit, "platform_key_id": platform_key_id, "to": to}))

    # ── PlatformPolicies ─────────────────────────────────────

    def platform_policies_create(self, body: models.PlatformCreatePolicyRequest | None = None) -> models.PlatformPolicyResponse:
        """POST /api/v1/platform/policies"""
        path = "/api/v1/platform/policies"
        return cast("models.PlatformPolicyResponse", self._request("POST", path, body))

    def platform_policies_delete(self, id: str) -> Any:
        """DELETE /api/v1/platform/policies/{id}"""
        path = f"/api/v1/platform/policies/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def platform_policies_get(self, id: str) -> models.PlatformPolicyResponse:
        """GET /api/v1/platform/policies/{id}"""
        path = f"/api/v1/platform/policies/{quote(id, safe='')}"
        return cast("models.PlatformPolicyResponse", self._request("GET", path))

    def platform_policies_list(self) -> list[models.PlatformPolicyResponse]:
        """GET /api/v1/platform/policies"""
        path = "/api/v1/platform/policies"
        return cast("list[models.PlatformPolicyResponse]", self._request("GET", path))

    def platform_policies_update(self, id: str, body: models.PlatformUpdatePolicyRequest | None = None) -> models.PlatformPolicyResponse:
        """PUT /api/v1/platform/policies/{id}"""
        path = f"/api/v1/platform/policies/{quote(id, safe='')}"
        return cast("models.PlatformPolicyResponse", self._request("PUT", path, body))

    # ── PlatformRoles ─────────────────────────────────────

    def platform_roles_create(self, body: models.PlatformCreateRoleRequest | None = None) -> models.Role:
        """POST /api/v1/platform/roles"""
        path = "/api/v1/platform/roles"
        return cast("models.Role", self._request("POST", path, body))

    def platform_roles_delete(self, id: str) -> Any:
        """DELETE /api/v1/platform/roles/{id}"""
        path = f"/api/v1/platform/roles/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def platform_roles_get(self, id: str) -> models.Role:
        """GET /api/v1/platform/roles/{id}"""
        path = f"/api/v1/platform/roles/{quote(id, safe='')}"
        return cast("models.Role", self._request("GET", path))

    def platform_roles_list(self) -> list[models.Role]:
        """GET /api/v1/platform/roles"""
        path = "/api/v1/platform/roles"
        return cast("list[models.Role]", self._request("GET", path))

    def platform_roles_update(self, id: str, body: models.PlatformUpdateRoleRequest | None = None) -> models.Role:
        """PUT /api/v1/platform/roles/{id}"""
        path = f"/api/v1/platform/roles/{quote(id, safe='')}"
        return cast("models.Role", self._request("PUT", path, body))

    # ── PlatformTenants ─────────────────────────────────────

    def platform_tenants_create(self, body: models.PlatformProvisionTenantRequest | None = None) -> models.PlatformTenantResponse:
        """POST /api/v1/platform/tenants"""
        path = "/api/v1/platform/tenants"
        return cast("models.PlatformTenantResponse", self._request("POST", path, body))

    def platform_tenants_delete(self, id: str) -> Any:
        """DELETE /api/v1/platform/tenants/{id}"""
        path = f"/api/v1/platform/tenants/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def platform_tenants_get(self, id: str) -> models.PlatformTenantResponse:
        """GET /api/v1/platform/tenants/{id}"""
        path = f"/api/v1/platform/tenants/{quote(id, safe='')}"
        return cast("models.PlatformTenantResponse", self._request("GET", path))

    def platform_tenants_list(self) -> list[models.PlatformTenantResponse]:
        """GET /api/v1/platform/tenants"""
        path = "/api/v1/platform/tenants"
        return cast("list[models.PlatformTenantResponse]", self._request("GET", path))

    # ── PlatformUsers ─────────────────────────────────────

    def platform_users_create(self, body: models.PlatformCreateUserRequest | None = None) -> models.PlatformUser:
        """POST /api/v1/platform/users"""
        path = "/api/v1/platform/users"
        return cast("models.PlatformUser", self._request("POST", path, body))

    def platform_users_delete(self, id: str) -> Any:
        """DELETE /api/v1/platform/users/{id}"""
        path = f"/api/v1/platform/users/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def platform_users_get(self, id: str) -> models.PlatformUser:
        """GET /api/v1/platform/users/{id}"""
        path = f"/api/v1/platform/users/{quote(id, safe='')}"
        return cast("models.PlatformUser", self._request("GET", path))

    def platform_users_list(self) -> list[models.PlatformUser]:
        """GET /api/v1/platform/users"""
        path = "/api/v1/platform/users"
        return cast("list[models.PlatformUser]", self._request("GET", path))

    def platform_users_update(self, id: str, body: models.PlatformUpdateUserRequest | None = None) -> models.PlatformUser:
        """PUT /api/v1/platform/users/{id}"""
        path = f"/api/v1/platform/users/{quote(id, safe='')}"
        return cast("models.PlatformUser", self._request("PUT", path, body))

    # ── Policies ─────────────────────────────────────

    def policies_create(self, body: models.CreatePolicyRequest | None = None) -> models.PolicyDetailResponse:
        """POST /api/v1/policies"""
        path = "/api/v1/policies"
        return cast("models.PolicyDetailResponse", self._request("POST", path, body))

    def policies_delete(self, id: str) -> Any:
        """DELETE /api/v1/policies/{id}"""
        path = f"/api/v1/policies/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def policies_dry_run(self, body: models.DryRunPolicyRequest | None = None) -> models.DryRunPolicyResponse:
        """POST /api/v1/policies/dry-run"""
        path = "/api/v1/policies/dry-run"
        return cast("models.DryRunPolicyResponse", self._request("POST", path, body))

    def policies_get(self, id: str) -> models.PolicyDetailResponse:
        """GET /api/v1/policies/{id}"""
        path = f"/api/v1/policies/{quote(id, safe='')}"
        return cast("models.PolicyDetailResponse", self._request("GET", path))

    def policies_list(self) -> list[models.PolicyResponse]:
        """GET /api/v1/policies"""
        path = "/api/v1/policies"
        return cast("list[models.PolicyResponse]", self._request("GET", path))

    def policies_list_versions(self, id: str) -> list[models.PolicyVersionResponse]:
        """GET /api/v1/policies/{id}/versions"""
        path = f"/api/v1/policies/{quote(id, safe='')}/versions"
        return cast("list[models.PolicyVersionResponse]", self._request("GET", path))

    def policies_patch(self, id: str, body: models.UpdatePolicyRequest | None = None) -> models.PolicyDetailResponse:
        """PATCH /api/v1/policies/{id}"""
        path = f"/api/v1/policies/{quote(id, safe='')}"
        return cast("models.PolicyDetailResponse", self._request("PATCH", path, body))

    def policies_rollback(self, id: str, version: str, body: Any = None) -> models.PolicyDetailResponse:
        """POST /api/v1/policies/{id}/rollback/{version}"""
        path = f"/api/v1/policies/{quote(id, safe='')}/rollback/{quote(version, safe='')}"
        return cast("models.PolicyDetailResponse", self._request("POST", path, body))

    # ── PolicyTemplates ─────────────────────────────────────

    def policy_templates_install(self, id: str, body: Any = None) -> models.InstallPolicyTemplateResponse:
        """POST /api/v1/policy-templates/{id}/install"""
        path = f"/api/v1/policy-templates/{quote(id, safe='')}/install"
        return cast("models.InstallPolicyTemplateResponse", self._request("POST", path, body))

    def policy_templates_list(self) -> list[models.PolicyTemplate]:
        """GET /api/v1/policy-templates"""
        path = "/api/v1/policy-templates"
        return cast("list[models.PolicyTemplate]", self._request("GET", path))

    # ── Projections ─────────────────────────────────────

    def projections_delete(self, name: str) -> models.ProjectionActionResponse:
        """DELETE /api/v1/projections/{name}"""
        path = f"/api/v1/projections/{quote(name, safe='')}"
        return cast("models.ProjectionActionResponse", self._request("DELETE", path))

    def projections_list_partitions(self, name: str, *, limit: int | None = None, q: str | None = None) -> models.ListProjectionPartitionsResponse:
        """GET /api/v1/projections/{name}/partitions"""
        path = f"/api/v1/projections/{quote(name, safe='')}/partitions"
        return cast("models.ListProjectionPartitionsResponse", self._request("GET", path, None, params={"limit": limit, "q": q}))

    # ── Projects ─────────────────────────────────────

    def projects_create(self, body: models.ProjectNameRequest | None = None) -> models.Project:
        """POST /api/v1/projects"""
        path = "/api/v1/projects"
        return cast("models.Project", self._request("POST", path, body))

    def projects_delete(self, id: str) -> models.DeleteProjectResponse:
        """DELETE /api/v1/projects/{id}"""
        path = f"/api/v1/projects/{quote(id, safe='')}"
        return cast("models.DeleteProjectResponse", self._request("DELETE", path))

    def projects_list(self) -> list[models.Project]:
        """GET /api/v1/projects"""
        path = "/api/v1/projects"
        return cast("list[models.Project]", self._request("GET", path))

    def projects_update(self, id: str, body: models.ProjectNameRequest | None = None) -> models.Project:
        """PUT /api/v1/projects/{id}"""
        path = f"/api/v1/projects/{quote(id, safe='')}"
        return cast("models.Project", self._request("PUT", path, body))

    # ── Roles ─────────────────────────────────────

    def roles_create(self, body: models.CreateRoleRequest | None = None) -> models.Role:
        """POST /api/v1/roles"""
        path = "/api/v1/roles"
        return cast("models.Role", self._request("POST", path, body))

    def roles_delete(self, id: str) -> Any:
        """DELETE /api/v1/roles/{id}"""
        path = f"/api/v1/roles/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def roles_delete_policies(self, id: str, policy_id: str) -> Any:
        """DELETE /api/v1/roles/{id}/policies/{policy_id}"""
        path = f"/api/v1/roles/{quote(id, safe='')}/policies/{quote(policy_id, safe='')}"
        return self._request("DELETE", path)

    def roles_get(self, id: str) -> models.Role:
        """GET /api/v1/roles/{id}"""
        path = f"/api/v1/roles/{quote(id, safe='')}"
        return cast("models.Role", self._request("GET", path))

    def roles_list(self) -> list[models.RoleResponse]:
        """GET /api/v1/roles"""
        path = "/api/v1/roles"
        return cast("list[models.RoleResponse]", self._request("GET", path))

    def roles_list_policies(self, id: str) -> models.RolePoliciesResponse:
        """GET /api/v1/roles/{id}/policies"""
        path = f"/api/v1/roles/{quote(id, safe='')}/policies"
        return cast("models.RolePoliciesResponse", self._request("GET", path))

    def roles_patch(self, id: str, body: models.UpdateRoleRequest | None = None) -> models.Role:
        """PATCH /api/v1/roles/{id}"""
        path = f"/api/v1/roles/{quote(id, safe='')}"
        return cast("models.Role", self._request("PATCH", path, body))

    def roles_policies(self, id: str, body: models.AssignPolicyRequest | None = None) -> Any:
        """POST /api/v1/roles/{id}/policies"""
        path = f"/api/v1/roles/{quote(id, safe='')}/policies"
        return self._request("POST", path, body)

    # ── Runs ─────────────────────────────────────

    def runs_list_streams(self, id: str) -> models.RunStreamsResponse:
        """GET /api/v1/runs/{id}/streams"""
        path = f"/api/v1/runs/{quote(id, safe='')}/streams"
        return cast("models.RunStreamsResponse", self._request("GET", path))

    # ── Secrets ─────────────────────────────────────

    def secrets_create(self, body: models.CreateSecretRequest | None = None, *, x_ironflow_environment: str) -> models.SecretInfoResponse:
        """POST /api/v1/secrets"""
        path = "/api/v1/secrets"
        return cast("models.SecretInfoResponse", self._request("POST", path, body, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    def secrets_delete(self, name: str, *, x_ironflow_environment: str) -> Any:
        """DELETE /api/v1/secrets/{name}"""
        path = f"/api/v1/secrets/{quote(name, safe='')}"
        return self._request("DELETE", path, None, headers={"X-Ironflow-Environment": x_ironflow_environment})

    def secrets_get(self, name: str, *, x_ironflow_environment: str) -> models.SecretInfoResponse:
        """GET /api/v1/secrets/{name}"""
        path = f"/api/v1/secrets/{quote(name, safe='')}"
        return cast("models.SecretInfoResponse", self._request("GET", path, None, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    def secrets_list(self, *, x_ironflow_environment: str) -> list[models.SecretInfoResponse]:
        """GET /api/v1/secrets"""
        path = "/api/v1/secrets"
        return cast("list[models.SecretInfoResponse]", self._request("GET", path, None, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    def secrets_patch(self, name: str, body: models.PatchSecretRequest | None = None, *, x_ironflow_environment: str) -> models.SecretInfoResponse:
        """PATCH /api/v1/secrets/{name}"""
        path = f"/api/v1/secrets/{quote(name, safe='')}"
        return cast("models.SecretInfoResponse", self._request("PATCH", path, body, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    def secrets_update(self, name: str, body: models.UpdateSecretRequest | None = None, *, x_ironflow_environment: str) -> models.SecretInfoResponse:
        """PUT /api/v1/secrets/{name}"""
        path = f"/api/v1/secrets/{quote(name, safe='')}"
        return cast("models.SecretInfoResponse", self._request("PUT", path, body, headers={"X-Ironflow-Environment": x_ironflow_environment}))

    # ── Tenants ─────────────────────────────────────

    def tenants_list(self) -> list[models.TenantListItem]:
        """GET /api/v1/tenants"""
        path = "/api/v1/tenants"
        return cast("list[models.TenantListItem]", self._request("GET", path))

    def tenants_provision(self, body: models.ProvisionTenantRequest | None = None) -> models.ProvisionTenantResponse:
        """POST /api/v1/tenants/provision"""
        path = "/api/v1/tenants/provision"
        return cast("models.ProvisionTenantResponse", self._request("POST", path, body))

    # ── Users ─────────────────────────────────────

    def users_create(self, body: models.CreateUserRequest | None = None) -> models.UserResponse:
        """POST /api/v1/users"""
        path = "/api/v1/users"
        return cast("models.UserResponse", self._request("POST", path, body))

    def users_delete(self, id: str) -> Any:
        """DELETE /api/v1/users/{id}"""
        path = f"/api/v1/users/{quote(id, safe='')}"
        return self._request("DELETE", path)

    def users_get(self, id: str) -> models.UserResponse:
        """GET /api/v1/users/{id}"""
        path = f"/api/v1/users/{quote(id, safe='')}"
        return cast("models.UserResponse", self._request("GET", path))

    def users_list(self) -> list[models.UserResponse]:
        """GET /api/v1/users"""
        path = "/api/v1/users"
        return cast("list[models.UserResponse]", self._request("GET", path))

    def users_patch(self, id: str, body: models.UpdateUserRequest | None = None) -> models.UserResponse:
        """PATCH /api/v1/users/{id}"""
        path = f"/api/v1/users/{quote(id, safe='')}"
        return cast("models.UserResponse", self._request("PATCH", path, body))

    def users_patch_password(self, id: str, body: models.ChangePasswordRequest | None = None) -> Any:
        """PATCH /api/v1/users/{id}/password"""
        path = f"/api/v1/users/{quote(id, safe='')}/password"
        return self._request("PATCH", path, body)

    # ── Workers ─────────────────────────────────────

    def workers_heartbeat(self, worker_id: str, body: models.HeartbeatRequest | None = None) -> models.WorkerStatusResponse:
        """POST /api/v1/workers/{workerId}/heartbeat"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/heartbeat"
        return cast("models.WorkerStatusResponse", self._request("POST", path, body))

    def workers_list(self) -> models.ListWorkersResponse:
        """GET /api/v1/workers"""
        path = "/api/v1/workers"
        return cast("models.ListWorkersResponse", self._request("GET", path))

    def workers_list_jobs(self, worker_id: str, *, available: int | None = None) -> models.JobBatchResponse | None:
        """GET /api/v1/workers/{workerId}/jobs"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/jobs"
        return cast("models.JobBatchResponse | None", self._request("GET", path, None, params={"available": available}))

    def workers_register(self, worker_id: str, body: models.RegisterRequest | None = None) -> models.WorkerStatusResponse:
        """POST /api/v1/workers/{workerId}/register"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/register"
        return cast("models.WorkerStatusResponse", self._request("POST", path, body))

    def workers_update_heartbeat(self, worker_id: str, body: models.HeartbeatRequest | None = None) -> models.WorkerStatusResponse:
        """PUT /api/v1/workers/{workerId}/heartbeat"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/heartbeat"
        return cast("models.WorkerStatusResponse", self._request("PUT", path, body))

    def workers_update_jobs(self, worker_id: str, job_id: str, body: models.JobUpdateRequest | None = None) -> models.WorkerStatusResponse:
        """PUT /api/v1/workers/{workerId}/jobs/{jobId}"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/jobs/{quote(job_id, safe='')}"
        return cast("models.WorkerStatusResponse", self._request("PUT", path, body))

    def workers_update_jobs_ack(self, worker_id: str, job_id: str, body: models.JobAckRequest | None = None) -> models.WorkerStatusResponse:
        """PUT /api/v1/workers/{workerId}/jobs/{jobId}/ack"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/jobs/{quote(job_id, safe='')}/ack"
        return cast("models.WorkerStatusResponse", self._request("PUT", path, body))

    def workers_update_register(self, worker_id: str, body: models.RegisterRequest | None = None) -> models.WorkerStatusResponse:
        """PUT /api/v1/workers/{workerId}/register"""
        path = f"/api/v1/workers/{quote(worker_id, safe='')}/register"
        return cast("models.WorkerStatusResponse", self._request("PUT", path, body))
