# Generated from ironflow/v1/audit.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import audit_pb
from .audit_pb import GetAuditTrailRequest, GetAuditTrailResponse, GetAuthAuditTrailRequest, GetAuthAuditTrailResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class AuditService(Protocol):
    async def get_audit_trail(self, request: GetAuditTrailRequest, ctx: RequestContext[GetAuditTrailRequest, GetAuditTrailResponse], /) -> GetAuditTrailResponse:
        """
        Get paginated audit trail for a run
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_auth_audit_trail(self, request: GetAuthAuditTrailRequest, ctx: RequestContext[GetAuthAuditTrailRequest, GetAuthAuditTrailResponse], /) -> GetAuthAuditTrailResponse:
        """
        Get paginated auth audit trail for an organization
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in audit_pb.desc().services if s.type_name == 'ironflow.v1.AuditService')

class AuditServiceASGIApplication(ConnectASGIApplication[AuditService]):
    def __init__(
        self,
        service: AuditService | AsyncGenerator[AuditService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/ironflow.v1.AuditService/GetAuditTrail": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAuditTrail",
                        service_name="ironflow.v1.AuditService",
                        input=GetAuditTrailRequest,
                        output=GetAuditTrailResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_audit_trail,
                ),
                "/ironflow.v1.AuditService/GetAuthAuditTrail": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAuthAuditTrail",
                        service_name="ironflow.v1.AuditService",
                        input=GetAuthAuditTrailRequest,
                        output=GetAuthAuditTrailResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_auth_audit_trail,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ironflow.v1.AuditService"


class AuditServiceClient(ConnectClient):
    async def get_audit_trail(
        self,
        request: GetAuditTrailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetAuditTrailResponse:
        """
        Get paginated audit trail for a run
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAuditTrail",
                service_name="ironflow.v1.AuditService",
                input=GetAuditTrailRequest,
                output=GetAuditTrailResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_auth_audit_trail(
        self,
        request: GetAuthAuditTrailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetAuthAuditTrailResponse:
        """
        Get paginated auth audit trail for an organization
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAuthAuditTrail",
                service_name="ironflow.v1.AuditService",
                input=GetAuthAuditTrailRequest,
                output=GetAuthAuditTrailResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class AuditServiceSync(Protocol):
    def get_audit_trail(self, request: GetAuditTrailRequest, ctx: RequestContext[GetAuditTrailRequest, GetAuditTrailResponse], /) -> GetAuditTrailResponse:
        """
        Get paginated audit trail for a run
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_auth_audit_trail(self, request: GetAuthAuditTrailRequest, ctx: RequestContext[GetAuthAuditTrailRequest, GetAuthAuditTrailResponse], /) -> GetAuthAuditTrailResponse:
        """
        Get paginated auth audit trail for an organization
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in audit_pb.desc().services if s.type_name == 'ironflow.v1.AuditService')

class AuditServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AuditServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/ironflow.v1.AuditService/GetAuditTrail": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAuditTrail",
                        service_name="ironflow.v1.AuditService",
                        input=GetAuditTrailRequest,
                        output=GetAuditTrailResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_audit_trail,
                ),
                "/ironflow.v1.AuditService/GetAuthAuditTrail": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAuthAuditTrail",
                        service_name="ironflow.v1.AuditService",
                        input=GetAuthAuditTrailRequest,
                        output=GetAuthAuditTrailResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_auth_audit_trail,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ironflow.v1.AuditService"


class AuditServiceClientSync(ConnectClientSync):
    def get_audit_trail(
        self,
        request: GetAuditTrailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetAuditTrailResponse:
        """
        Get paginated audit trail for a run
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAuditTrail",
                service_name="ironflow.v1.AuditService",
                input=GetAuditTrailRequest,
                output=GetAuditTrailResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_auth_audit_trail(
        self,
        request: GetAuthAuditTrailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetAuthAuditTrailResponse:
        """
        Get paginated auth audit trail for an organization
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAuthAuditTrail",
                service_name="ironflow.v1.AuditService",
                input=GetAuthAuditTrailRequest,
                output=GetAuthAuditTrailResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
