# Generated from ironflow/v1/query.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.3.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


_ExecuteSQLRequestFields: TypeAlias = Literal["query", "timeout_ms", "max_rows"]

class ExecuteSQLRequest(Message[_ExecuteSQLRequestFields]):
    """
    ```proto
    message ironflow.v1.ExecuteSQLRequest
    ```

    Attributes:
        query:
            ```proto
            string query = 1;
            ```
        timeout_ms:
            default 5000, max 30000

            ```proto
            int32 timeout_ms = 2;
            ```
        max_rows:
            default 1000, max 10000

            ```proto
            int32 max_rows = 3;
            ```
    """

    __slots__ = ("query", "timeout_ms", "max_rows")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            query: str = "",
            timeout_ms: int = 0,
            max_rows: int = 0,
        ) -> None:
            pass

        query: str
        timeout_ms: int
        max_rows: int

_ExecuteSQLResponseFields: TypeAlias = Literal["columns", "rows", "total_rows"]

class ExecuteSQLResponse(Message[_ExecuteSQLResponseFields]):
    """
    ```proto
    message ironflow.v1.ExecuteSQLResponse
    ```

    Attributes:
        columns:
            ```proto
            repeated string columns = 1;
            ```
        rows:
            ```proto
            repeated ironflow.v1.SQLRow rows = 2;
            ```
        total_rows:
            ```proto
            int32 total_rows = 3;
            ```
    """

    __slots__ = ("columns", "rows", "total_rows")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            columns: list[str] | None = None,
            rows: list[SQLRow] | None = None,
            total_rows: int = 0,
        ) -> None:
            pass

        columns: list[str]
        rows: list[SQLRow]
        total_rows: int

_SQLRowFields: TypeAlias = Literal["values"]

class SQLRow(Message[_SQLRowFields]):
    """
    ```proto
    message ironflow.v1.SQLRow
    ```

    Attributes:
        values:
            ```proto
            repeated string values = 1;
            ```
    """

    __slots__ = ("values",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            values: list[str] | None = None,
        ) -> None:
            pass

        values: list[str]


_DESC = file_desc(
    b'\n\x17ironflow/v1/query.proto\x12\x0bironflow.v1"c\n\x11ExecuteSQLRequest\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n\ntimeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\x12\x19\n\x08max_rows\x18\x03 \x01(\x05R\x07maxRows"v\n\x12ExecuteSQLResponse\x12\x18\n\x07columns\x18\x01 \x03(\tR\x07columns\x12\'\n\x04rows\x18\x02 \x03(\x0b2\x13.ironflow.v1.SQLRowR\x04rows\x12\x1d\n\ntotal_rows\x18\x03 \x01(\x05R\ttotalRows" \n\x06SQLRow\x12\x16\n\x06values\x18\x01 \x03(\tR\x06values2b\n\x0cQueryService\x12R\n\nExecuteSQL\x12\x1e.ironflow.v1.ExecuteSQLRequest\x1a\x1f.ironflow.v1.ExecuteSQLResponse"\x03\x90\x02\x01B:Z8github.com/sahina/ironflow/api/go/ironflow/v1;ironflowv1b\x06proto3',
    [],
    {
        "ExecuteSQLRequest": ExecuteSQLRequest,
        "ExecuteSQLResponse": ExecuteSQLResponse,
        "SQLRow": SQLRow,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `ironflow/v1/query.proto`."""
    return _DESC
