# Generated from ironflow/v1/webhook.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService
from protobuf.wkt import Empty

from . import webhook_pb
from .webhook_pb import CreateWebhookSourceRequest, DeleteWebhookSourceRequest, DisableWebhookSignatureVerificationRequest, ExpireWebhookSecretPrevRequest, GetWebhookSourceRequest, ListWebhookDeliveriesRequest, ListWebhookDeliveriesResponse, ListWebhookSourcesRequest, ListWebhookSourcesResponse, RotateWebhookIngestTokenRequest, RotateWebhookSecretRequest, TestWebhookVerifyConfigRequest, TestWebhookVerifyConfigResponse, UpdateWebhookSourceRequest, WebhookSource

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class WebhookService(Protocol):
    async def create_webhook_source(self, request: CreateWebhookSourceRequest, ctx: RequestContext[CreateWebhookSourceRequest, WebhookSource], /) -> WebhookSource:
        """
        Create a new webhook source
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_webhook_source(self, request: GetWebhookSourceRequest, ctx: RequestContext[GetWebhookSourceRequest, WebhookSource], /) -> WebhookSource:
        """
        Get a single webhook source by ID
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_webhook_sources(self, request: ListWebhookSourcesRequest, ctx: RequestContext[ListWebhookSourcesRequest, ListWebhookSourcesResponse], /) -> ListWebhookSourcesResponse:
        """
        List all webhook sources
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_webhook_source(self, request: UpdateWebhookSourceRequest, ctx: RequestContext[UpdateWebhookSourceRequest, WebhookSource], /) -> WebhookSource:
        """
        Update editable fields on a webhook source. Does not change verify_secret.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def rotate_webhook_secret(self, request: RotateWebhookSecretRequest, ctx: RequestContext[RotateWebhookSecretRequest, WebhookSource], /) -> WebhookSource:
        """
        Rotate the verify_secret. Promotes the prior current secret to the
        prev slot for the grace window. Empty new secret is rejected — use
        DisableWebhookSignatureVerification.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def expire_webhook_secret_prev(self, request: ExpireWebhookSecretPrevRequest, ctx: RequestContext[ExpireWebhookSecretPrevRequest, WebhookSource], /) -> WebhookSource:
        """
        Force-expire the previous secret immediately. Idempotent.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def disable_webhook_signature_verification(self, request: DisableWebhookSignatureVerificationRequest, ctx: RequestContext[DisableWebhookSignatureVerificationRequest, WebhookSource], /) -> WebhookSource:
        """
        Disable signature verification on a source. Preserves the prior
        current secret as prev for the grace window; after the window the
        source operates unsigned.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def rotate_webhook_ingest_token(self, request: RotateWebhookIngestTokenRequest, ctx: RequestContext[RotateWebhookIngestTokenRequest, WebhookSource], /) -> WebhookSource:
        """
        Rotate the per-source ingest token (ADR 0048). Replaces any existing
        token outright — there is no grace window, because the token lives
        only in the provider's URL field and is replaced by the same operator
        who rotated it. The new raw token is returned once, in
        WebhookSource.ingest_token, and is unrecoverable afterwards.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def test_webhook_verify_config(self, request: TestWebhookVerifyConfigRequest, ctx: RequestContext[TestWebhookVerifyConfigRequest, TestWebhookVerifyConfigResponse], /) -> TestWebhookVerifyConfigResponse:
        """
        TestWebhookVerifyConfig replays a captured delivery against a descriptor
        and reports what the server computed. A wrong signing template and a wrong
        secret both surface as "invalid signature" at delivery time, so this is
        how an operator tells them apart — it returns the signing string that was
        built alongside the signature, without persisting anything.

        Mutating-verb naming ("Test") is required: rbac.connectAction routes
        WebhookService methods by verb, and anything unmatched falls through to
        events:subscribe, which RoleViewer holds. This request carries a secret.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_webhook_source(self, request: DeleteWebhookSourceRequest, ctx: RequestContext[DeleteWebhookSourceRequest, Empty], /) -> Empty:
        """
        Delete a webhook source
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_webhook_deliveries(self, request: ListWebhookDeliveriesRequest, ctx: RequestContext[ListWebhookDeliveriesRequest, ListWebhookDeliveriesResponse], /) -> ListWebhookDeliveriesResponse:
        """
        List webhook deliveries with optional filtering
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in webhook_pb.desc().services if s.type_name == 'ironflow.v1.WebhookService')

class WebhookServiceASGIApplication(ConnectASGIApplication[WebhookService]):
    def __init__(
        self,
        service: WebhookService | AsyncGenerator[WebhookService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/ironflow.v1.WebhookService/CreateWebhookSource": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=CreateWebhookSourceRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_webhook_source,
                ),
                "/ironflow.v1.WebhookService/GetWebhookSource": Endpoint.unary(
                    method=MethodInfo(
                        name="GetWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=GetWebhookSourceRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_webhook_source,
                ),
                "/ironflow.v1.WebhookService/ListWebhookSources": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWebhookSources",
                        service_name="ironflow.v1.WebhookService",
                        input=ListWebhookSourcesRequest,
                        output=ListWebhookSourcesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_webhook_sources,
                ),
                "/ironflow.v1.WebhookService/UpdateWebhookSource": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=UpdateWebhookSourceRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_webhook_source,
                ),
                "/ironflow.v1.WebhookService/RotateWebhookSecret": Endpoint.unary(
                    method=MethodInfo(
                        name="RotateWebhookSecret",
                        service_name="ironflow.v1.WebhookService",
                        input=RotateWebhookSecretRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.rotate_webhook_secret,
                ),
                "/ironflow.v1.WebhookService/ExpireWebhookSecretPrev": Endpoint.unary(
                    method=MethodInfo(
                        name="ExpireWebhookSecretPrev",
                        service_name="ironflow.v1.WebhookService",
                        input=ExpireWebhookSecretPrevRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.expire_webhook_secret_prev,
                ),
                "/ironflow.v1.WebhookService/DisableWebhookSignatureVerification": Endpoint.unary(
                    method=MethodInfo(
                        name="DisableWebhookSignatureVerification",
                        service_name="ironflow.v1.WebhookService",
                        input=DisableWebhookSignatureVerificationRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.disable_webhook_signature_verification,
                ),
                "/ironflow.v1.WebhookService/RotateWebhookIngestToken": Endpoint.unary(
                    method=MethodInfo(
                        name="RotateWebhookIngestToken",
                        service_name="ironflow.v1.WebhookService",
                        input=RotateWebhookIngestTokenRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.rotate_webhook_ingest_token,
                ),
                "/ironflow.v1.WebhookService/TestWebhookVerifyConfig": Endpoint.unary(
                    method=MethodInfo(
                        name="TestWebhookVerifyConfig",
                        service_name="ironflow.v1.WebhookService",
                        input=TestWebhookVerifyConfigRequest,
                        output=TestWebhookVerifyConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.test_webhook_verify_config,
                ),
                "/ironflow.v1.WebhookService/DeleteWebhookSource": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=DeleteWebhookSourceRequest,
                        output=Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_webhook_source,
                ),
                "/ironflow.v1.WebhookService/ListWebhookDeliveries": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWebhookDeliveries",
                        service_name="ironflow.v1.WebhookService",
                        input=ListWebhookDeliveriesRequest,
                        output=ListWebhookDeliveriesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_webhook_deliveries,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ironflow.v1.WebhookService"


class WebhookServiceClient(ConnectClient):
    async def create_webhook_source(
        self,
        request: CreateWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Create a new webhook source
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=CreateWebhookSourceRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_webhook_source(
        self,
        request: GetWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> WebhookSource:
        """
        Get a single webhook source by ID
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=GetWebhookSourceRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_webhook_sources(
        self,
        request: ListWebhookSourcesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListWebhookSourcesResponse:
        """
        List all webhook sources
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWebhookSources",
                service_name="ironflow.v1.WebhookService",
                input=ListWebhookSourcesRequest,
                output=ListWebhookSourcesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def update_webhook_source(
        self,
        request: UpdateWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Update editable fields on a webhook source. Does not change verify_secret.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=UpdateWebhookSourceRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def rotate_webhook_secret(
        self,
        request: RotateWebhookSecretRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Rotate the verify_secret. Promotes the prior current secret to the
        prev slot for the grace window. Empty new secret is rejected — use
        DisableWebhookSignatureVerification.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RotateWebhookSecret",
                service_name="ironflow.v1.WebhookService",
                input=RotateWebhookSecretRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def expire_webhook_secret_prev(
        self,
        request: ExpireWebhookSecretPrevRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Force-expire the previous secret immediately. Idempotent.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExpireWebhookSecretPrev",
                service_name="ironflow.v1.WebhookService",
                input=ExpireWebhookSecretPrevRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def disable_webhook_signature_verification(
        self,
        request: DisableWebhookSignatureVerificationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Disable signature verification on a source. Preserves the prior
        current secret as prev for the grace window; after the window the
        source operates unsigned.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DisableWebhookSignatureVerification",
                service_name="ironflow.v1.WebhookService",
                input=DisableWebhookSignatureVerificationRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def rotate_webhook_ingest_token(
        self,
        request: RotateWebhookIngestTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Rotate the per-source ingest token (ADR 0048). Replaces any existing
        token outright — there is no grace window, because the token lives
        only in the provider's URL field and is replaced by the same operator
        who rotated it. The new raw token is returned once, in
        WebhookSource.ingest_token, and is unrecoverable afterwards.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RotateWebhookIngestToken",
                service_name="ironflow.v1.WebhookService",
                input=RotateWebhookIngestTokenRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def test_webhook_verify_config(
        self,
        request: TestWebhookVerifyConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TestWebhookVerifyConfigResponse:
        """
        TestWebhookVerifyConfig replays a captured delivery against a descriptor
        and reports what the server computed. A wrong signing template and a wrong
        secret both surface as "invalid signature" at delivery time, so this is
        how an operator tells them apart — it returns the signing string that was
        built alongside the signature, without persisting anything.

        Mutating-verb naming ("Test") is required: rbac.connectAction routes
        WebhookService methods by verb, and anything unmatched falls through to
        events:subscribe, which RoleViewer holds. This request carries a secret.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TestWebhookVerifyConfig",
                service_name="ironflow.v1.WebhookService",
                input=TestWebhookVerifyConfigRequest,
                output=TestWebhookVerifyConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_webhook_source(
        self,
        request: DeleteWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Empty:
        """
        Delete a webhook source
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=DeleteWebhookSourceRequest,
                output=Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_webhook_deliveries(
        self,
        request: ListWebhookDeliveriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListWebhookDeliveriesResponse:
        """
        List webhook deliveries with optional filtering
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWebhookDeliveries",
                service_name="ironflow.v1.WebhookService",
                input=ListWebhookDeliveriesRequest,
                output=ListWebhookDeliveriesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class WebhookServiceSync(Protocol):
    def create_webhook_source(self, request: CreateWebhookSourceRequest, ctx: RequestContext[CreateWebhookSourceRequest, WebhookSource], /) -> WebhookSource:
        """
        Create a new webhook source
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_webhook_source(self, request: GetWebhookSourceRequest, ctx: RequestContext[GetWebhookSourceRequest, WebhookSource], /) -> WebhookSource:
        """
        Get a single webhook source by ID
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_webhook_sources(self, request: ListWebhookSourcesRequest, ctx: RequestContext[ListWebhookSourcesRequest, ListWebhookSourcesResponse], /) -> ListWebhookSourcesResponse:
        """
        List all webhook sources
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_webhook_source(self, request: UpdateWebhookSourceRequest, ctx: RequestContext[UpdateWebhookSourceRequest, WebhookSource], /) -> WebhookSource:
        """
        Update editable fields on a webhook source. Does not change verify_secret.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def rotate_webhook_secret(self, request: RotateWebhookSecretRequest, ctx: RequestContext[RotateWebhookSecretRequest, WebhookSource], /) -> WebhookSource:
        """
        Rotate the verify_secret. Promotes the prior current secret to the
        prev slot for the grace window. Empty new secret is rejected — use
        DisableWebhookSignatureVerification.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def expire_webhook_secret_prev(self, request: ExpireWebhookSecretPrevRequest, ctx: RequestContext[ExpireWebhookSecretPrevRequest, WebhookSource], /) -> WebhookSource:
        """
        Force-expire the previous secret immediately. Idempotent.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def disable_webhook_signature_verification(self, request: DisableWebhookSignatureVerificationRequest, ctx: RequestContext[DisableWebhookSignatureVerificationRequest, WebhookSource], /) -> WebhookSource:
        """
        Disable signature verification on a source. Preserves the prior
        current secret as prev for the grace window; after the window the
        source operates unsigned.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def rotate_webhook_ingest_token(self, request: RotateWebhookIngestTokenRequest, ctx: RequestContext[RotateWebhookIngestTokenRequest, WebhookSource], /) -> WebhookSource:
        """
        Rotate the per-source ingest token (ADR 0048). Replaces any existing
        token outright — there is no grace window, because the token lives
        only in the provider's URL field and is replaced by the same operator
        who rotated it. The new raw token is returned once, in
        WebhookSource.ingest_token, and is unrecoverable afterwards.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def test_webhook_verify_config(self, request: TestWebhookVerifyConfigRequest, ctx: RequestContext[TestWebhookVerifyConfigRequest, TestWebhookVerifyConfigResponse], /) -> TestWebhookVerifyConfigResponse:
        """
        TestWebhookVerifyConfig replays a captured delivery against a descriptor
        and reports what the server computed. A wrong signing template and a wrong
        secret both surface as "invalid signature" at delivery time, so this is
        how an operator tells them apart — it returns the signing string that was
        built alongside the signature, without persisting anything.

        Mutating-verb naming ("Test") is required: rbac.connectAction routes
        WebhookService methods by verb, and anything unmatched falls through to
        events:subscribe, which RoleViewer holds. This request carries a secret.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_webhook_source(self, request: DeleteWebhookSourceRequest, ctx: RequestContext[DeleteWebhookSourceRequest, Empty], /) -> Empty:
        """
        Delete a webhook source
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_webhook_deliveries(self, request: ListWebhookDeliveriesRequest, ctx: RequestContext[ListWebhookDeliveriesRequest, ListWebhookDeliveriesResponse], /) -> ListWebhookDeliveriesResponse:
        """
        List webhook deliveries with optional filtering
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in webhook_pb.desc().services if s.type_name == 'ironflow.v1.WebhookService')

class WebhookServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: WebhookServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/ironflow.v1.WebhookService/CreateWebhookSource": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=CreateWebhookSourceRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_webhook_source,
                ),
                "/ironflow.v1.WebhookService/GetWebhookSource": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=GetWebhookSourceRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_webhook_source,
                ),
                "/ironflow.v1.WebhookService/ListWebhookSources": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListWebhookSources",
                        service_name="ironflow.v1.WebhookService",
                        input=ListWebhookSourcesRequest,
                        output=ListWebhookSourcesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_webhook_sources,
                ),
                "/ironflow.v1.WebhookService/UpdateWebhookSource": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=UpdateWebhookSourceRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_webhook_source,
                ),
                "/ironflow.v1.WebhookService/RotateWebhookSecret": EndpointSync.unary(
                    method=MethodInfo(
                        name="RotateWebhookSecret",
                        service_name="ironflow.v1.WebhookService",
                        input=RotateWebhookSecretRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.rotate_webhook_secret,
                ),
                "/ironflow.v1.WebhookService/ExpireWebhookSecretPrev": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExpireWebhookSecretPrev",
                        service_name="ironflow.v1.WebhookService",
                        input=ExpireWebhookSecretPrevRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.expire_webhook_secret_prev,
                ),
                "/ironflow.v1.WebhookService/DisableWebhookSignatureVerification": EndpointSync.unary(
                    method=MethodInfo(
                        name="DisableWebhookSignatureVerification",
                        service_name="ironflow.v1.WebhookService",
                        input=DisableWebhookSignatureVerificationRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.disable_webhook_signature_verification,
                ),
                "/ironflow.v1.WebhookService/RotateWebhookIngestToken": EndpointSync.unary(
                    method=MethodInfo(
                        name="RotateWebhookIngestToken",
                        service_name="ironflow.v1.WebhookService",
                        input=RotateWebhookIngestTokenRequest,
                        output=WebhookSource,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.rotate_webhook_ingest_token,
                ),
                "/ironflow.v1.WebhookService/TestWebhookVerifyConfig": EndpointSync.unary(
                    method=MethodInfo(
                        name="TestWebhookVerifyConfig",
                        service_name="ironflow.v1.WebhookService",
                        input=TestWebhookVerifyConfigRequest,
                        output=TestWebhookVerifyConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.test_webhook_verify_config,
                ),
                "/ironflow.v1.WebhookService/DeleteWebhookSource": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteWebhookSource",
                        service_name="ironflow.v1.WebhookService",
                        input=DeleteWebhookSourceRequest,
                        output=Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_webhook_source,
                ),
                "/ironflow.v1.WebhookService/ListWebhookDeliveries": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListWebhookDeliveries",
                        service_name="ironflow.v1.WebhookService",
                        input=ListWebhookDeliveriesRequest,
                        output=ListWebhookDeliveriesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_webhook_deliveries,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/ironflow.v1.WebhookService"


class WebhookServiceClientSync(ConnectClientSync):
    def create_webhook_source(
        self,
        request: CreateWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Create a new webhook source
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=CreateWebhookSourceRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_webhook_source(
        self,
        request: GetWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> WebhookSource:
        """
        Get a single webhook source by ID
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=GetWebhookSourceRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_webhook_sources(
        self,
        request: ListWebhookSourcesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListWebhookSourcesResponse:
        """
        List all webhook sources
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWebhookSources",
                service_name="ironflow.v1.WebhookService",
                input=ListWebhookSourcesRequest,
                output=ListWebhookSourcesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def update_webhook_source(
        self,
        request: UpdateWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Update editable fields on a webhook source. Does not change verify_secret.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=UpdateWebhookSourceRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def rotate_webhook_secret(
        self,
        request: RotateWebhookSecretRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Rotate the verify_secret. Promotes the prior current secret to the
        prev slot for the grace window. Empty new secret is rejected — use
        DisableWebhookSignatureVerification.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RotateWebhookSecret",
                service_name="ironflow.v1.WebhookService",
                input=RotateWebhookSecretRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def expire_webhook_secret_prev(
        self,
        request: ExpireWebhookSecretPrevRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Force-expire the previous secret immediately. Idempotent.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExpireWebhookSecretPrev",
                service_name="ironflow.v1.WebhookService",
                input=ExpireWebhookSecretPrevRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def disable_webhook_signature_verification(
        self,
        request: DisableWebhookSignatureVerificationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Disable signature verification on a source. Preserves the prior
        current secret as prev for the grace window; after the window the
        source operates unsigned.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DisableWebhookSignatureVerification",
                service_name="ironflow.v1.WebhookService",
                input=DisableWebhookSignatureVerificationRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def rotate_webhook_ingest_token(
        self,
        request: RotateWebhookIngestTokenRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> WebhookSource:
        """
        Rotate the per-source ingest token (ADR 0048). Replaces any existing
        token outright — there is no grace window, because the token lives
        only in the provider's URL field and is replaced by the same operator
        who rotated it. The new raw token is returned once, in
        WebhookSource.ingest_token, and is unrecoverable afterwards.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RotateWebhookIngestToken",
                service_name="ironflow.v1.WebhookService",
                input=RotateWebhookIngestTokenRequest,
                output=WebhookSource,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def test_webhook_verify_config(
        self,
        request: TestWebhookVerifyConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TestWebhookVerifyConfigResponse:
        """
        TestWebhookVerifyConfig replays a captured delivery against a descriptor
        and reports what the server computed. A wrong signing template and a wrong
        secret both surface as "invalid signature" at delivery time, so this is
        how an operator tells them apart — it returns the signing string that was
        built alongside the signature, without persisting anything.

        Mutating-verb naming ("Test") is required: rbac.connectAction routes
        WebhookService methods by verb, and anything unmatched falls through to
        events:subscribe, which RoleViewer holds. This request carries a secret.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TestWebhookVerifyConfig",
                service_name="ironflow.v1.WebhookService",
                input=TestWebhookVerifyConfigRequest,
                output=TestWebhookVerifyConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_webhook_source(
        self,
        request: DeleteWebhookSourceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Empty:
        """
        Delete a webhook source
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteWebhookSource",
                service_name="ironflow.v1.WebhookService",
                input=DeleteWebhookSourceRequest,
                output=Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_webhook_deliveries(
        self,
        request: ListWebhookDeliveriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListWebhookDeliveriesResponse:
        """
        List webhook deliveries with optional filtering
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWebhookDeliveries",
                service_name="ironflow.v1.WebhookService",
                input=ListWebhookDeliveriesRequest,
                output=ListWebhookDeliveriesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
